import React, {useMemo, useState} from 'react';
import {Pressable, SafeAreaView, StyleSheet, Text, View} from 'react-native';
import poisJson from './src/assets/pois.json';
import pathsJson from './src/assets/paths.json';
import {DestinationPicker} from './src/components/DestinationPicker';
import {NavigationPanel} from './src/components/NavigationPanel';
import {useDeviceLocation} from './src/hooks/useDeviceLocation';
import {NavigationMap} from './src/map/NavigationMap';
import {buildEdges, buildNodes, connectPois} from './src/routing/graph';
import {createRouteGeoJson, findRoute, nearestRouteDistance} from './src/routing/router';
import {FeatureCollection, GeoFeature, Route} from './src/types/navigation';
const pois=poisJson as unknown as FeatureCollection;const paths=pathsJson as unknown as FeatureCollection;
export default function App(){const location=useDeviceLocation();const [destination,setDestination]=useState<GeoFeature>();const [following,setFollowing]=useState(true);const graph=useMemo(()=>{const nodes=buildNodes(paths);return {nodes,edges:buildEdges(paths,nodes),connections:connectPois(pois,nodes)};},[]);const startPoi=useMemo(()=>location.coordinate ? pois.features.reduce((closest, poi) => { const [lon, lat] = poi.geometry.coordinates as [number, number]; const [currentLon, currentLat] = location.coordinate!; return (lon-currentLon)**2+(lat-currentLat)**2 < ((closest.geometry.coordinates as [number, number])[0]-currentLon)**2+((closest.geometry.coordinates as [number, number])[1]-currentLat)**2 ? poi : closest; }) : pois.features[0]!, [location.coordinate]);const route:Route|undefined=useMemo(()=>destination?findRoute(startPoi.properties.id,destination.properties.id,graph.connections,graph.nodes,graph.edges,'pedestrian') ?? undefined:undefined,[destination,graph,startPoi]);const routeGeo=route?createRouteGeoJson(route):undefined;const remaining=route&&location.coordinate?nearestRouteDistance(route,location.coordinate):route?.totalDistance;return <SafeAreaView style={styles.screen}><NavigationMap pois={pois} route={routeGeo} destination={destination?.geometry.coordinates as [number,number]|undefined} location={location.coordinate} follow={following}/><DestinationPicker pois={pois.features} onSelect={poi=>{setDestination(poi);setFollowing(true);}}/><View style={styles.actions}><Pressable onPress={()=>setFollowing(true)} style={styles.recenter} accessibilityLabel="Re-center on my location"><Text style={styles.recenterText}>◎</Text></Pressable></View>{location.error&&<View style={styles.error}><Text style={styles.errorText}>{location.error}</Text></View>}<NavigationPanel destination={destination?.properties.name} distance={remaining} onStop={()=>setDestination(undefined)}/></SafeAreaView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#eef2ee'},actions:{position:'absolute',right:18,bottom:180},recenter:{width:52,height:52,alignItems:'center',justifyContent:'center',borderRadius:26,backgroundColor:'#fff',elevation:4},recenterText:{fontSize:30,color:'#1f4931'},error:{position:'absolute',top:128,left:16,right:16,backgroundColor:'#fff3f2',padding:12,borderRadius:10},errorText:{color:'#9b1c1c',textAlign:'center'}});
