platform :ios, '15.1'
prepare_react_native_project!
target 'UniWay' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath], :app_path => "#{Pod::Config.instance.installation_root}/..")
  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])
  end
end
